In [1]:
import torch

x = torch.randn(7,512)

/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


In [2]:
x = torch.nn.functional.normalize(x,dim=1)

In [3]:
x.shape

torch.Size([7, 512])

In [4]:
x2 = x*x

In [5]:
sum(x2[0])

tensor(1.0000)

In [6]:
from models import CosClassifier

Failed to import cuda/cpp RPEIndexFunction


/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/utils/_pytree.py:185: FutureWarning: optree is installed but the version is too old to support PyTorch Dynamo in C++ pytree. C++ pytree support is disabled. Please consider upgrading optree using `python3 -m pip install --upgrade 'optree>=0.13.0'`.
  warnings.warn(


running install
running bdist_egg
running egg_info
creating rpe_index.egg-info
writing rpe_index.egg-info/PKG-INFO
writing dependency_links to rpe_index.egg-info/dependency_links.txt
writing top-level names to rpe_index.egg-info/top_level.txt
writing manifest file 'rpe_index.egg-info/SOURCES.txt'


/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:79: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:79: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
       

reading manifest file 'rpe_index.egg-info/SOURCES.txt'
writing manifest file 'rpe_index.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11.1-arm64/egg
running install_lib
running build_ext
building 'rpe_index_cpp' extension
creating /Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/build/temp.macosx-11.1-arm64-cpython-310


Emitting ninja build file /Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/build/temp.macosx-11.1-arm64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Traceback (most recent call last):
  File "/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2209, in _run_ninja_build
    subprocess.run(
  File "/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/setup.py", line 16, in <module>
    setup(name='rpe_index',
  File "/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/se

[1/1] c++ -MMD -MF /Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/build/temp.macosx-11.1-arm64-cpython-310/rpe_index.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/seominjae/anaconda3/envs/midterm/include -arch arm64 -fPIC -O2 -isystem /Users/seominjae/anaconda3/envs/midterm/include -arch arm64 -I/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/include -I/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/include/TH -I/Users/seominjae/anaconda3/envs/midterm/lib/python3.10/site-packages/torch/include/THC -I/Users/seominjae/anaconda3/envs/midterm/include/python3.10 -c -c /Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/rpe_index.cpp -o /Users/seominjae/rl/models/vit_kprpe/RPE/rpe_ops/build/temp.macosx-11.1-arm64-cpython-310/rpe_index.o -fopenmp -O3 -DTORCH_API_INCLUDE_E

/Users/seominjae/rl/models/vit_kprpe/RPE/__init__.py:22: UserWarning: 
[WARNING] Failed to install `rpe_ops`. Please check the installation script.
  warnings.warn(RED_STR.format("\n[WARNING] Failed to install `rpe_ops`. "


In [14]:
cos = CosClassifier()

In [8]:
x = torch.randn((3,512))
margin, cos = cos(x)

In [9]:
margin.shape

torch.Size([7])

In [11]:
o = cos*cos

In [12]:
sum(o[0])

tensor(0.0324, grad_fn=<AddBackward0>)

In [16]:
w = cos.kernel

In [17]:
w.shape

torch.Size([512, 7])

In [18]:
kernel = torch.nn.functional.normalize(w,dim=0,p=2)

In [19]:
kernel.shape

torch.Size([512, 7])

In [21]:
sum((kernel*kernel)[:,0])

tensor(1.0000, grad_fn=<AddBackward0>)

In [22]:
x

tensor([[ 0.6900,  1.0156,  0.3313,  ..., -0.2203,  1.0751,  0.4939],
        [ 0.7002, -0.5001, -1.1010,  ..., -0.1428,  0.4320, -0.8311],
        [ 1.0060,  0.2601,  0.2018,  ..., -0.5737, -2.2217,  1.7573]])

In [23]:
x.shape

torch.Size([3, 512])

In [24]:
x = torch.nn.functional.normalize(x,dim=1)

In [25]:
x2 = x*x

In [26]:
sum(x2[0])

tensor(1.)

In [27]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [28]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
torch.sum(x,dim=1)

tensor([ 6, 15])